services:
  app:
    build: .
    # image: model-registry:latest
    ports:
      - "8080:8080"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=model_registry
      - DB_HOST=postgres
      - DB_PORT=5432
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=model_registry
